apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ffmpeg
  name: ffmpeg-deployment

spec:
  selector:
    matchLabels:
      app: ffmpeg
  replicas: 1
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      volumes:
        - name: codefile
          hostPath:
            path: /dev/video0
      containers:
      - name: ffmpeg
        securityContext:
          privileged: true
        image: jrottenberg/ffmpeg
        imagePullPolicy: IfNotPresent
        args: ["-i","/dev/video0","-s","640x360","-vcodec","libx264","-max_delay","10","-r","5","-b:v","10000k","-b:a","10000k","-f","flv","rtmp://192.168.50.63/live/pi01"]
        volumeMounts:
        - mountPath: /dev/video0
          name: codefile
