apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srs
  name: srs-deployment

spec:
  selector:
    matchLabels:
      app: srs
  replicas: 1
  template:
    metadata:
      labels:
        app: srs
    spec:
      containers:
      - name: srs
        image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
        imagePullPolicy: IfNotPresent
        command: ["./objs/srs"]
        args: ["-c","conf/docker.conf"]
        ports:
        - containerPort: 1935
          hostPort: 1935
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 1985
          hostPort: 1985

  
          

      

